//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chet_
    {
        public int ID { get; set; }
        public Nullable<int> IDBug { get; set; }
        public Nullable<double> Sum { get; set; }
        public DateTime dateOt { get; set; }
        public DateTime dateDo { get; set; }
        public Nullable<int> IDStrahKomp { get; set; }
    
        public virtual Polzovatel_ Polzovatel_ { get; set; }
        public virtual StrahovaiKompania_ StrahovaiKompania_ { get; set; }
    }
}
