//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanneAnalizatora_
    {
        public int IDDanni { get; set; }
        public Nullable<int> IDAnalizator { get; set; }
        public DateTime DateVremaPostupYslugi { get; set; }
        public string VremaVapol { get; set; }
        public Nullable<int> IDLaboranta { get; set; }
        public Nullable<int> IDYslugaVZakaze { get; set; }
    
        public virtual Analizator_ Analizator_ { get; set; }
        public virtual Polzovatel_ Polzovatel_ { get; set; }
        public virtual YslugiVZakazah_ YslugiVZakazah_ { get; set; }
    }
}
