//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class histor_
    {
        public int IDHistor { get; set; }
        public Nullable<int> IDPolzovatel { get; set; }
        public string ip { get; set; }
        public DateTime DataNach { get; set; }
        public DateTime lastenter { get; set; }
        public Nullable<int> IDPrichina { get; set; }
    
        public virtual IDPrichina_ IDPrichina_ { get; set; }
        public virtual Polzovatel_ Polzovatel_ { get; set; }
    }
}
