//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedLabEntities : DbContext
    {
        public MedLabEntities()
            : base("name=MedLabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analizator_> Analizator_ { get; set; }
        public virtual DbSet<Chet_> Chet_ { get; set; }
        public virtual DbSet<DanneAnalizatora_> DanneAnalizatora_ { get; set; }
        public virtual DbSet<histor_> histor_ { get; set; }
        public virtual DbSet<IDPrichina_> IDPrichina_ { get; set; }
        public virtual DbSet<Polzovatel_> Polzovatel_ { get; set; }
        public virtual DbSet<Rol_> Rol_ { get; set; }
        public virtual DbSet<Status_> Status_ { get; set; }
        public virtual DbSet<StrahovaiKompania_> StrahovaiKompania_ { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeStrahPolic_> TypeStrahPolic_ { get; set; }
        public virtual DbSet<Yslugi_> Yslugi_ { get; set; }
        public virtual DbSet<YslugiVZakazah_> YslugiVZakazah_ { get; set; }
        public virtual DbSet<Zakaz_> Zakaz_ { get; set; }
    }
}
