//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovatel_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polzovatel_()
        {
            this.Chet_ = new HashSet<Chet_>();
            this.DanneAnalizatora_ = new HashSet<DanneAnalizatora_>();
            this.histor_ = new HashSet<histor_>();
            this.Zakaz_ = new HashSet<Zakaz_>();
        }
    
        public int IDPolzovatel { get; set; }
        public string name { get; set; }
        public string familia { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public DateTime dateHappyBiz { get; set; }
        public Nullable<int> SeriaPasPort { get; set; }
        public Nullable<int> NomerPasPort { get; set; }
        public string telefon { get; set; }
        public string Email { get; set; }
        public string numberStrahPolic { get; set; }
        public Nullable<int> IDtypetrahPolic { get; set; }
        public Nullable<int> IDStrahovaiKompania { get; set; }
        public Nullable<int> IDRol { get; set; }
        public string kartinka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chet_> Chet_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanneAnalizatora_> DanneAnalizatora_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<histor_> histor_ { get; set; }
        public virtual Rol_ Rol_ { get; set; }
        public virtual StrahovaiKompania_ StrahovaiKompania_ { get; set; }
        public virtual TypeStrahPolic_ TypeStrahPolic_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz_> Zakaz_ { get; set; }
    }
}
