//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrahovaiKompania_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StrahovaiKompania_()
        {
            this.Chet_ = new HashSet<Chet_>();
            this.Polzovatel_ = new HashSet<Polzovatel_>();
        }
    
        public int IDStrahovaiKompania { get; set; }
        public string name { get; set; }
        public string adres { get; set; }
        public double inn { get; set; }
        public double rc { get; set; }
        public Nullable<int> bik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chet_> Chet_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovatel_> Polzovatel_ { get; set; }
    }
}
