//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class YslugiVZakazah_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YslugiVZakazah_()
        {
            this.DanneAnalizatora_ = new HashSet<DanneAnalizatora_>();
        }
    
        public int IDYslugaVZakaze { get; set; }
        public int IDZakaz { get; set; }
        public int IDYslugi { get; set; }
        public int IDStatus { get; set; }
        public string ShtihKod { get; set; }
        public string Result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanneAnalizatora_> DanneAnalizatora_ { get; set; }
        public virtual Status_ Status_ { get; set; }
        public virtual Yslugi_ Yslugi_ { get; set; }
        public virtual Zakaz_ Zakaz_ { get; set; }
    }
}
