//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yslugi_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yslugi_()
        {
            this.YslugiVZakazah_ = new HashSet<YslugiVZakazah_>();
        }
    
        public int IDYslugi { get; set; }
        public string Service { get; set; }
        public double Price { get; set; }
        public int SrokVapol { get; set; }
        public double Ot { get; set; }
        public double Do { get; set; }
        public int metka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YslugiVZakazah_> YslugiVZakazah_ { get; set; }
    }
}
