//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz_()
        {
            this.YslugiVZakazah_ = new HashSet<YslugiVZakazah_>();
        }
    
        public int IDZakaz { get; set; }
        public DateTime DateSozdania { get; set; }
        public int IDPolzovatel { get; set; }
        public int IDStatus { get; set; }
        public int VapolnenieZakaza { get; set; }
    
        public virtual Polzovatel_ Polzovatel_ { get; set; }
        public virtual Status_ Status_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YslugiVZakazah_> YslugiVZakazah_ { get; set; }
    }
}
